import 'package:isar/isar.dart';

part 'attachment.g.dart';

@collection
class Attachment {
  Id id = Isar.autoIncrement;

  @Index()
  late String uuid;

  @Index()
  late String messageId;

  @enumerated
  late AttachmentType type;

  /// Local file path
  late String localPath;

  /// Original filename
  late String fileName;

  /// File size in bytes
  int fileSize = 0;

  /// MIME type
  String? mimeType;

  /// For images: width/height
  int? width;
  int? height;

  /// For audio/video: duration in seconds
  double? durationSeconds;

  /// Optional cloud URL (if synced)
  String? cloudUrl;

  /// Whether this attachment was generated by the app
  bool isGenerated = false;

  late DateTime createdAt;

  Map<String, dynamic> toJson() => {
        'uuid': uuid,
        'messageId': messageId,
        'type': type.name,
        'localPath': localPath,
        'fileName': fileName,
        'fileSize': fileSize,
        'mimeType': mimeType,
        'width': width,
        'height': height,
        'durationSeconds': durationSeconds,
        'cloudUrl': cloudUrl,
        'isGenerated': isGenerated,
        'createdAt': createdAt.toIso8601String(),
      };

  static Attachment fromJson(Map<String, dynamic> json) {
    return Attachment()
      ..uuid = json['uuid'] as String
      ..messageId = json['messageId'] as String
      ..type = AttachmentType.values.byName(json['type'] as String)
      ..localPath = json['localPath'] as String
      ..fileName = json['fileName'] as String
      ..fileSize = json['fileSize'] as int? ?? 0
      ..mimeType = json['mimeType'] as String?
      ..width = json['width'] as int?
      ..height = json['height'] as int?
      ..durationSeconds = (json['durationSeconds'] as num?)?.toDouble()
      ..cloudUrl = json['cloudUrl'] as String?
      ..isGenerated = json['isGenerated'] as bool? ?? false
      ..createdAt = DateTime.parse(json['createdAt'] as String);
  }
}

enum AttachmentType {
  image,
  audio,
  video,
  document,
}
